#!/bin/sh
# Simple start script for the httpi web-server

# 0. Define safe path
PATH=/bin:/usr/bin
#
## CUSTOMIZE AS REQUIRED
#
# 1. Downgrade to a non-root user account (adjust as required)
runAs=nobody

# 2. Location of httpi server program
HTTPI=/data/app/httpi/httpi

# 3. Extra path(s) for anything we wish to have but don't want to add to the
#    cgi scripts ourselves
for d in /data/app/bin
do
    [ -d $d ] && PATH=$PATH:$d
done

export PATH
unset DISPLAY SGE_ROOT SGE_CELL  # a bit extra safety

#---------------------------------------------------------------------------
# The following lines provide the necessary info for adding a startup script
# according to the Linux Standard Base Specification (LSB).
#
### BEGIN INIT INFO
# Provides:       httpi-xmlqstat
# Required-Start: $network $remote_fs
# Should-Start:   network-remotefs
# Required-Stop:
# Default-Start:  3 5
# Default-Stop: 0 1 2 6
# Description:  start httpi for extra xmlqstat support
### END INIT INFO
#---------------------------------------------------------------------------

# this script should run as 'runAs'
if [ "$UID" -eq 0 -a "${runAs:=root}" != root ]
then
    exec sudo -S -u $runAs $0 $@
    exitcode=$?       # retain exitcode

    [ "$exitcode" == 0 ] || {
        echo "could not change to $runAs"
        exit $exitcode
    }
fi

daemon=$HTTPI
desc="httpi webserver"

# logging
LOG=/var/log/httpi
LOG=/dev/null

#
# check that the daemon program is installed
#
check_installed()
{
    [ -f $daemon -a -x $daemon ] || {
        echo "$daemon not found"
        exit 5      # LSB compliant exit status - program is not installed
    }
}


# with second argument, take as the name of the httpi server
if [ "$#" -ge 2 ]
then
    daemon=$2
    check_installed
fi


set -e
case "$1" in
start)
    check_installed

    echo -n "Starting $desc: "
    $daemon >> $LOG 2>&1 &
    echo "httpi ($daemon)"
    ;;

stop)
    echo -n "Stopping $desc: "
    # get pid
    pid=`ps aux | awk '{if (/httpi:/ && !/awk/) print $2}'`
    if [ -z "$pid" ]
    then
        echo "process not found"
    else
        echo "sending TERM signal"
        kill -15 $pid
    fi
    ;;

restart)
    ## Stop (if running) and start anew
    shift
    check_installed
    $0 stop
    $0 start $@
    ;;

*)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
# -------------------------------------------------------------- end-of-file
