#!/bin/sh
#
# Simple start script for the Cocoon server engine
#
## CUSTOMIZE AS REQUIRED
#
# require GridEngine information for later queries
# (only required when using the command-generator)
: ${SGE_ROOT:=/opt/grid}
: ${SGE_CELL:=default}

JAVA_HOME=/usr/lib/jvm/java
COCOON_HOME=/data/app/cocoon

export SGE_ROOT SGE_CELL JAVA_HOME COCOON_HOME

## Init the Grid Engine path/environment variables
## so our script can access Grid Engine commands
if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]
then
    . $SGE_ROOT/$SGE_CELL/common/settings.sh
else
    unset SGE_ROOT SGE_CELL
fi

# extra path for anything we wish to use via the java CommandGenerator
PATH=$PATH:/data/app/bin

unset DISPLAY  # a bit extra safety

##
## System start scripts typically run as root user,
## downgrade to a non-root user account. Adjust as required
##
runas_user=cfdadmin
# -------------------------------------------------------------------------
# this script should run as 'runas_user'
#
if [ "$UID" -eq 0 -a "${runas_user:=root}" != root ]
then
    exec sudo -S -u $runas_user $0 $@
    exitcode=$?       # retain exitcode

    [ "$exitcode" == 0 ] || {
       echo "could not change to $runas_user"
       exit $exitcode
    }
fi

daemon=$COCOON_HOME/cocoon.sh
name=cocoon
desc="Apache Cocoon"

# logging
LOG=/var/log/cocoon
LOG=/dev/null

[ -f $daemon -a -x $daemon ] || {
    echo "$daemon not found"
    exit 5      # LSB compliant exit status - program is not installed
}

test -f $daemon || exit 0
set -e
case "$1" in
start)
    echo -n "Starting $desc: "
    $daemon servlet >> $LOG 2>&1 &
    echo "$name"
    ;;

stop)
    echo "Stopping $desc: $name"
    # get pid
    pid=`ps -f -C java | awk '{if (/cocoon/) print $2}'`
    if [ -z "$pid" ]
    then
        echo "process not found"
    else
        kill -15 $pid
    fi
    ;;

restart)
    ## Stop (if running) and start anew
    $0 stop
    $0 start
    ;;

*)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;
esac
exit 0
# ------------------------------------------------------------- end-of-file
