#!/bin/sh

## Simple start script for the httpi web-server

## CUSTOMIZE AS REQUIRED
#
# require GridEngine information for later queries
: ${SGE_ROOT:=/opt/n1ge6}

HTTPI_HOME=/data/app/httpi
PATH=/bin:/usr/bin:$SGE_ROOT/bin/`$SGE_ROOT/util/arch`

# extra path for anything we wish to but don't want to add to the
# cgi scripts ourselves
PATH=$PATH:/data/app/bin

export SGE_ROOT PATH
unset DISPLAY  # a bit extra safety

##
## System start scripts typically run as root user,
## downgrade to a non-root user account. Adjust as needed
##
runas_user=nobody
# -------------------------------------------------------------------------
# this script should run as 'runas_user'
#
if [ "$UID" -eq 0 -a "${runas_user:=root}" != root ]
then
   exec sudo -S -u $runas_user $0 $@
   exitcode=$?       # retain exitcode

   [ "$exitcode" == 0 ] || {
      echo "could not change to $runas_user"
      exit $exitcode
   }
fi

daemon=$HTTPI_HOME/httpi
name=httpi
desc="httpi webserver"

# logging
LOG=/var/log/httpi
LOG=/dev/null

[ -f $daemon -a -x $daemon ] || {
   echo "$daemon not found"
   exit 5      # LSB compliant exit status - program is not installed
}

test -f $daemon || exit 0
set -e
case "$1" in
start)
   echo -n "Starting $desc: "
   $daemon >> $LOG 2>&1 &
   echo "$name"
   ;;

stop)
   echo "Usage: $0 {start}" >&2
   exit 1
   ;;

*)
   echo "Usage: $0 {start}" >&2
   exit 1
   ;;
esac
exit 0
# ------------------------------------------------------------- end-of-file
