#!/bin/sh

## Simple start/stop script for the perl daemon that caches
## Grid Engine XML status data for the "xml-qstat" web application

## CUSTOMIZE AS NEEDED
: ${SGE_ROOT:=/opt/grid}
: ${SGE_CELL:=default}

CACHE_SGE_XML_HOME=/opt/xml-qstat/scripts

export SGE_ROOT SGE_CELL CACHE_SGE_XML_HOME

##
## System start scripts typically run as root user,
## downgrade to a non-root user account. Adjust as needed
##
runas_user=cfdadmin
# -----------------------------------------------------------------------------
# this script should run as 'runas_user'
#
if [ "$UID" -eq 0 -a "${runas_user:=root}" != root ]
then
    exec sudo -S -u $runas_user $0 $@
    exitcode=$?       # retain exitcode

    [ "$exitcode" == 0 ] || {
        echo "could not change to $runas_user"
        exit $exitcode
    }
fi

## Init the Grid Engine path/environment variables
## so our script can access Grid Engine commands
if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]
then
    . $SGE_ROOT/$SGE_CELL/common/settings.sh
fi

daemon=$CACHE_SGE_XML_HOME/sge-xml-cacher.pl
name=sge-xml-cacher
desc="GridEngine XML Status Cache Daemon"

[ -f $daemon -a -x $daemon ] || {
    echo "$daemon not found"
    exit 5      # LSB compliant exit status - program is not installed
}

case "$1" in
start)
    echo -n "Starting $desc: "
    $daemon -d
    echo "$name"
    ;;

stop)
    echo -n "Stopping $desc: "
    $daemon -k
    echo "$name"
    ;;

*)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
# ------------------------------------------------------------- end-of-file
